### ISSUE TITLE
Upgrade to `first-chunk-stream@2.0.0`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/strip-bom-stream#1]
@nfroidure Would you be willing to do it? I'm not entirely sure what changes needs doing.

**Comment by nfroidure** [comment]
Just did it. It could require a major update since the module reports errors in the callback, is now back-pressure aware and has a different behavior with too small streams.

Also found some errors in the first-chunk-stream readme file https://github.com/sindresorhus/first-chunk-stream/pull/3

**Comment by sindresorhus** [comment]
I added the backpressure awareness to the release notes, but not sure what else is breaking: https://github.com/sindresorhus/strip-bom-stream/releases/tag/v2.0.0 Mind adding? :)
