### ISSUE TITLE
Package Import results in Error: [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by igalgh** [sindresorhus/strip-bom-stream#5]
Hello
I'm trying to import and use `strip-bom-stream` from a project based on:
https://www.npmjs.com/package/typescript-express-starter
I'm importing it via:
```js
import stripBomStream from 'strip-bom-stream'
```
Then using it as in the npm page example.
Not sure why, but only for this package I get the following error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: .../backend/node_modules/strip-bom-stream/index.js
require() of ES modules is not supported.
require() of .../backend/node_modules/strip-bom-stream/index.js from .../backend/src/server.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from .../backend/node_modules/strip-bom-stream/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/9r/l8skj1hn3hgcmy5x8yl7hykh0000gn/T/ts-node-dev-hook-14357029147098777.js:114:20)
    at Object.nodeDevHook [as .js] (.../backend/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (.../backend/src/server.ts:28:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
[ERROR] 19:55:54 Error: Must use import to load ES Module: .../backend/node_modules/strip-bom-stream/index.js
```

Any idea what's the issue or what I'm doing wrong?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by igalgh** [comment]
@sindresorhus Thanks for the link.

I use `ts-node-dev` to run the project. 
The page you sent points me to https://github.com/TypeStrong/ts-node/issues/1007
I tried several of the suggested solutions, none seems to resolve it.
Do you think I have a chance to make this specific `import` work?

**Comment by sindresorhus** [comment]
I'm using ts-node with ESM successfully in many projects.

https://github.com/sindresorhus/got/blob/6c7ebab3674fbf8a21275cfe9e06f71740219c05/tsconfig.json#L21-L25

**Comment by igalgh** [comment]
This is my new tsConfig with the suggested changes (against what it was prior to trying to import `strip-bom-stream`):
![Screen Shot 2022-09-21 at 5 41 03 PM](https://user-images.githubusercontent.com/1245766/191534834-54deaf2c-8eef-4c6a-a421-35ef34f989c0.png)

The relevant package.json part is:
```
  "module": "ESNext",
  "type": "module",
  "engines": {
    "node": ">=14.20.0"
  },
```
My nodemon line for running it is:
```
"exec": "ts-node-dev --experimental-specifier-resolution=node --respawn --trace-warnings -r tsconfig-paths/register --transpile-only src/server.ts"
```
If you see anything obvious I'd be grateful

**Comment by vincentwinkel** [comment]
I have the same issue and cannot fix it.

**Comment by jordanst3wart** [comment]
yeah, this is a bit of a pain. I'm replacing stip-bom-stream with sed $'s/\xEF\xBB\xBF//g' data.csv . I don't want to use an experimental compiler options for a tiny library

**Comment by Maxim-Mazurok** [comment]
> yeah, this is a bit of a pain. I'm replacing stip-bom-stream with sed $'s/\xEF\xBB\xBF//g' data.csv . I don't want to use an experimental compiler options for a tiny library

I'm using v4 of this library, which is not pure ESM, so have no issues with it in my CJS project
